controller_list:
  - name: fake_PortaalRobot_controller
    type: $(arg fake_execution_type)
    joints:
      - horizontal_arm_joint
      - vertical_arm_joint
initial:  # Define initial robot poses.
  - group: PortaalRobot
    pose: Home